/*
 * File: app/view/DrawPanel.js
 * Date: Wed Jan 04 2012 11:15:13 GMT+0900 (JST)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('Draw.view.DrawPanel', {
    extend: 'Draw.view.ui.DrawPanel',
    alias: 'widget.drawpanel',
    layout: 'fit',

    items: [
        Ext.create('Ext.draw.Component', {
            viewBox: false,
            itemId: 'drawCompo'
        })
    ],

    initComponent: function() {

        var me = this;

        me.callParent(arguments);
    }

});
