/*
 * File: app/view/Viewport.js
 * Date: Wed Jan 04 2012 14:35:27 GMT+0900 (JST)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('Draw.view.Viewport', {
    extend: 'Draw.view.ui.Viewport',

    initComponent: function() {
        var me = this;
        me.callParent(arguments);
    }
});