/*
 * File: app/view/ui/DrawPanel.js
 * Date: Fri Jan 06 2012 15:13:22 GMT+0900 (JST)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Draw.view.ui.DrawPanel', {
    extend: 'Ext.panel.Panel',

    title: 'Draw Area',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'selectTool',
                            enableToggle: true,
                            iconCls: 'draw-tb-select',
                            toggleGroup: 'tools'
                        },
                        {
                            xtype: 'button',
                            itemId: 'lineTool',
                            enableToggle: true,
                            iconCls: 'draw-tb-line',
                            toggleGroup: 'tools'
                        },
                        {
                            xtype: 'button',
                            itemId: 'rectTool',
                            enableToggle: true,
                            iconCls: 'draw-tb-rect',
                            toggleGroup: 'tools'
                        },
                        {
                            xtype: 'button',
                            itemId: 'textTool',
                            enableToggle: true,
                            iconCls: 'draw-tb-text',
                            toggleGroup: 'tools'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'borderColorTool',
                            text: 'Border Color',
                            menu: {
                                xtype: 'colormenu',
                                itemId: 'borderColorMenu'
                            }
                        },
                        {
                            xtype: 'button',
                            itemId: 'fillColorTool',
                            text: 'Fill Color',
                            menu: {
                                xtype: 'colormenu',
                                itemId: 'fillColorMenu'
                            }
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }
});