/*
 * File: app/view/ui/Viewport.js
 * Date: Fri Jan 06 2012 15:13:22 GMT+0900 (JST)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Draw.view.ui.Viewport', {
    extend: 'Ext.container.Viewport',
    requires: [
        'Draw.view.DrawPanel'
    ],

    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'drawpanel',
                    region: 'center'
                },
                {
                    xtype: 'container',
                    width: 200,
                    layout: {
                        type: 'border'
                    },
                    region: 'east',
                    items: [
                        {
                            xtype: 'panel',
                            title: 'My Panel',
                            region: 'center'
                        },
                        {
                            xtype: 'panel',
                            height: 238,
                            title: 'My Panel',
                            region: 'north'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }
});